url:
  rails_home_url: "https://rubyonrails.org/"
  rails_tutorial_url: "https://www.railstutorial.org/"
  rails_help_url: "https://www.railstutorial.org/help"
  rails_book_url: "https://www.railstutorial.org/book"
  rails_contact_url: "https://www.railstutorial.org/contact"
  rails_new_url: "https://news.learnenough.com/"
  rails_screencasts_url: "https://screencasts.railstutorial.org/"
  learn_enough_url: "https://www.learnenough.com/"
  author_url: "https://www.michaelhartl.com/"
validates:
  max_name: 10
  min_email: 20
  max_email: 255
  min_password: 6
regex:
  VALID_EMAIL_REGEX: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'

paginate:
  limit: 10
